version: "3"

services:
  devicepasswords:
    image: ghcr.io/varbin/devicepasswords:trunk
    build: ..
    environment:
      DP_OIDC_DISCOVERY_URL: "http://127.0.0.1:8080/realms/master/.well-known/openid-configuration"
      DP_OIDC_CLIENT_ID: "device-password-manager"
      DP_OIDC_CLIENT_SECRET: "BBpwYZEtC3IT9zfvLlulBuaegK5Bi2no"  # Add your secret here
      DP_PASSWORD_HASH: "bcrypt"
      DP_SQLALCHEMY_DATABASE_URI: "postgresql://postgres:postgres@127.0.0.1/postgres"
      GUNICORN_CMD_ARGS: "--bind=127.0.0.1:5000"
    depends_on: [ postgres, keycloak ]
    # Only required as devicepasswords and keyloak run on the same machine as
    # containers. If your computer has an external hostname, you can replace
    # all references to 127.0.0.1:5000 and 127.0.0.1:8000 with your external
    # hostname.
    network_mode: host