"""Add login column to tokens.

Revision ID: dd50cf0133d0
Revises: 3a2d8d25b18e
Create Date: 2024-01-30 23:25:40.366719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd50cf0133d0'
down_revision: Union[str, None] = 'efe87d7792f3'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(), nullable=False))
        batch_op.create_unique_constraint('login_unique', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint('login_unique', type_='unique')
        batch_op.drop_column('login')
    # ### end Alembic commands ###
