on: [push, pull_request]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff Check
        uses: jpetrucciani/ruff-check@0.1.0

